### ISSUE TITLE
[Requesting Change]: Changes required in the task

### ISSUE THREAD

**Issue by DarthBenro008** [AmanVarshney01/naruto-svg-creator#1]
# The Task

Build a Figma plugin **using shadcn components**, i.e: your plugin design should have shadcn components like button.

Eg:
![image](https://github.com/user-attachments/assets/63533b30-fbc8-4947-b7e9-4068074ffbb6)

The buttons and dropdown menu here must be shadcn components, refer https://ui.shadcn.com/docs/components/button

Requirements:
- Your plugin must use tailwindCSS
- Your plugin must make use of shadcn

Great efforts so far! Looking forward to the completed task 😃

**Comment by AmanVarshney01** [comment]
Task completed: Figma plugin built using shadcn components and TailwindCSS as requested. Ready for review.

**Comment by DarthBenro008** [comment]
Thanks @AmanVarshney01 ! Do check your email 😉
